### ISSUE TITLE
US Autocomplete Client.JS will throw error when "payload.suggestions" is null

### ISSUE THREAD

**Issue by cmincarelli** [smartystreets/smartystreets-javascript-sdk#1]
smartystreets-javascript-sdk, version 1.0.5

When sending an address that is complete, with a stateFilter, and cityFilter the API backend returns "null" for payload.suggestions. There is no error checking in place for this, and the module throws at Client.js:50:31  when attempting to execute payload.suggestion.map(..)

Given this request (issued by the Autocomplete SDK)

```
Request {
  baseUrl: '',
  payload: undefined,
  headers: { 'Content-Type': 'application/json' },
  parameters: 
   { prefix: '411 Walnut Street BMB 8431',
     suggestions: 10,
     city_filter: 'Green Cove Springs',
     state_filter: 'FL',
     prefer: undefined,
     prefer_ratio: undefined,
     geolocate: undefined,
     geolocate_precision: undefined } }
```

The result is

```
{ suggestions: null }
```

The error is

```
TypeError: Cannot read property 'map' of null
    at buildSuggestionsFromResponse (../node_modules/smartystreets-javascript-sdk/src/us_autocomplete/Client.js:50:31)
    at sender.send.then.response (../node_modules/smartystreets-javascript-sdk/src/us_autocomplete/Client.js:26:22)
    at tryCallOne (.../node_modules/promise/lib/core.js:37:12)
    at .../node_modules/promise/lib/core.js:123:15
    at flush (.../node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

The solution to this issue:
```
function buildSuggestionsFromResponse(payload) {
  // payload may be null!
  if (typeof payload.suggestions === "null") {
    payload.suggestions = [];
  }
  return payload.suggestions.map(suggestion => new Suggestion(suggestion));
}
```

I would be happy to submit a PR if you require one.

**Comment by cmincarelli** [comment]
Actually - it should be "if (payload.suggestions === null) {"

**Comment by cbuchert** [comment]
Thanks for finding this. If you want to make a pull request with tests for
this case, I'll review it and we'll get it all patched up.

**Comment by cbuchert** [comment]
@cmincarelli I created a pull request for this issue. You can see it [here](https://github.com/smartystreets/smartystreets-javascript-sdk/pull/2). Thanks for finding this and bringing it up!

**Comment by cbuchert** [comment]
#2
