### ISSUE TITLE
Privacy configuration to protect credentials while using Javascript SDK

### ISSUE THREAD

**Issue by rachanamamillapalli** [smartystreets/smartystreets-javascript-sdk#20]
```
const SmartyStreetsSDK = require("smartystreets-javascript-sdk");
const SmartyStreetsCore = SmartyStreetsSDK.core;
const Lookup = SmartyStreetsSDK.usAutocompletePro.Lookup;

// US Autocomplete Pro only supports using Website Keys
let websiteKey = "put your website key here";
const credentials = new SmartyStreetsCore.SharedCredentials(websiteKey);

let client = SmartyStreetsCore.buildClient.usAutocompletePro(credentials);
```

When executing this code, the network tab in the browser shows **credentials** also. Is there a way we can protect this info from logging?

**Comment by rachanamamillapalli** [comment]
![SDK_Example](https://user-images.githubusercontent.com/9112473/95908495-c7143300-0dba-11eb-82b2-cda546cf4720.jpeg)

**Comment by camiblanch** [comment]
The website key is listed here which is correct behavior. The [website key](https://smartystreets.com/docs/cloud/authentication#htmlkeys) is associated with a hostname that you set on your [SmartyStreets account page](https://account.smartystreets.com/#keys). This restricts that key to only work on the specified host. As long as your hostname for that key isn't set to be something like `*`, which works for any hostname, then you are secure.

I found [this explanation](https://security.stackexchange.com/a/194112) of API keys helpful and the principals in it apply to the SmartyStreets website keys.

**Comment by rachanamamillapalli** [comment]
Right, but then any user can have access to this (hostname, website key) combination and in turn access the API. This shouldn't be the case, right?

**Comment by SunSparc** [comment]
@rachanamamillapalli, even if a user has your website key, they will only be able to use it if they have access to your dns and are able to setup a host with the same name one associated with your website key.

**Comment by mdwhatcott** [comment]
Also, @rachanamamillapalli - website keys are stringently rate-limited per client, another risk-minimizing factor.

**Comment by premasisp** [comment]
@SunSparc @mdwhatcott Above means someone can attack from inside or from outside if they managed to get in to our  DNS , Typically the authId is ranked as critical PII data which shouldn't be exposed in Network tab , Does your SDK support passing the header via request param or some Authentication header ?

**Comment by mdwhatcott** [comment]
@premasisp - Good question. The APIs currently only support authenticating via the query string. Your suggestion to add support for the Authentication header is an interesting one and we will discuss it.

**Comment by joliver** [comment]
The canonical way to perform authentication here is via the `Authorization` HTTP request header. At the present time the various backend APIs do not (yet) support that. Part of this was to avoid the extra round-trip OPTIONS request to the server. As some (near?) future point we may decide to support the `Authorization` header, but at this stage, it's only via query string parameters.
