### ISSUE TITLE
Shared credentials cannot be used in batches with a length greater than 1 or when using the US Extract API

### ISSUE THREAD

**Issue by rachanamamillapalli** [smartystreets/smartystreets-javascript-sdk#22]
https://github.com/smartystreets/smartystreets-javascript-sdk/blob/master/examples/us_street.js

I have followed this example and have been trying to validate a batch of address, where my batch size can be anywhere between 1-3. However, the `client.send(batch)` gives an error message.

**Comment by camiblanch** [comment]
Hi, can you share more details about the setup and error message?

**Comment by rachanamamillapalli** [comment]
@camiblanch My setup:
`const SmartyStreetsSDK = require("smartystreets-javascript-sdk");
const SmartyStreetsCore = SmartyStreetsSDK.core;
const Lookup = SmartyStreetsSDK.usStreet.Lookup;
let key = "websiteKey";
const credentials = new SmartyStreetsCore.SharedCredentials(key);
let client = SmartyStreetsCore.buildClient.usStreet(credentials);`

----
`let batch = new SmartyStreetsSDK.core.Batch();`

And I added 2 lookups to this batch. 
` let lookup = new Lookup();
    lookup.inputId = inputId;
    lookup.street = street;
    lookup.city = city;
    lookup.state = state;
    lookup.zipCode = zipCode; `

And then `client.send(batch)` gave me the error: "Shared credentials cannot be used in batches with a length greater than 1 or when using the US Extract API." 

<img width="802" alt="Screenshot 2020-10-21 at 3 35 46 AM" src="https://user-images.githubusercontent.com/9112473/96649311-85513280-134e-11eb-87de-38e369cb5781.png">

**Comment by rachanamamillapalli** [comment]
@camiblanch I see the error message here - https://github.com/smartystreets/smartystreets-javascript-sdk/blob/master/src/SigningSender.js#L14 
Any update on this? Currently blocked due to this issue.

**Comment by joliver** [comment]
We will not be changing the authentication model to accommodate the passing of multiple addresses (or using our US Extract API) using shared (website) authentication.

If you're using node.js, you should still be able to use secret key authentication which bypasses this restriction.

**Comment by rachanamamillapalli** [comment]
@joliver Are you suggesting to use `SmartyStreetsCore.StaticCredentials(authId, authToken);` instead of `SmartyStreetsCore.SharedCredentials(websiteKey)` ?

**Comment by joliver** [comment]
Correct, use `SmartyStreetsCore.StaticCredentials(authId, authToken);`

**Comment by rachanamamillapalli** [comment]
Could you update the examples here then https://github.com/smartystreets/smartystreets-javascript-sdk/blob/master/examples/us_street.js

**Comment by joliver** [comment]
Updated.

**Comment by rachanamamillapalli** [comment]
@joliver Oddly when I use authId, authToken it throws "Error: Unauthorized: The credentials were provided incorrectly or did not match any existing active credentials." This is the call I see in my network tab `https://us-street.api.smartystreets.com/street-address?agent=smartystreets+(sdk:javascript@1.6.0)&auth-id=<>&auth-token=<>`

The dependency I added is  "smartystreets-javascript-sdk": "^1.5.0" but not sure why I see 1.6.0 in the network tab.

However, the same URL works when I make a call via Postman.

**Comment by liampeng1** [comment]
I am having the same issue

**Comment by dave-smartystreets** [comment]
it looks like you're attempting to use your server credentials (i.e. `authId` and `authToken`) in a browser application.  The best  practice for this is to NOT use these credentials in the browser.  These credentials should never be exposed on the web.

Instead, you should go back to using your website key.  As mentioned earlier by @joliver, you can only validate one address at a time using this code example in a browser application. This is why you were getting that first error you reported (`Error: Shared credentials cannot be used in batches with a length greater than 1 or when using the US Extract API`).

Alternatively, if you must have batch processing and you have server access, consider placing your batch request code on your server.  You can then use the server credentials (`authId` and `authToken`) to make your request and THEN pass the validation response up to the browser application. 

We will review our documentation and code comments to make it more clear.

**Comment by dave-smartystreets** [comment]
Here are the unchanged code comments.  They clearly define the use of the credentials for server to server communications and client side (browser) requests.

![Screen Shot 2020-10-29 at 9 22 23 AM](https://user-images.githubusercontent.com/73613048/97594545-66931180-19c8-11eb-827e-bda3ce325a92.png)
