### ISSUE TITLE
Cannot authorize

### ISSUE THREAD

**Issue by liampeng1** [smartystreets/smartystreets-javascript-sdk#23]
Every time I try to send a request I get an error saying it is unauthorized despite me using the same auth-id and auth-token in both postman and curl requests successfully.

I added some logs into the package and this is what I get:

> console.log
    { data: 'Unauthorized (1587658904)\n',
      status: 401,
      statusText: 'Unauthorized',
      headers: { 'content-type': 'text/plain; charset=utf-8' },
      config:
       { adapter: [Function: xhrAdapter],
         transformRequest: { '0': [Function: transformRequest] },
         transformResponse: { '0': [Function: transformResponse] },
         timeout: 10000,
         xsrfCookieName: 'XSRF-TOKEN',
         xsrfHeaderName: 'X-XSRF-TOKEN',
         maxContentLength: -1,
         validateStatus: [Function: validateStatus],
         headers:
          { Accept: 'application/json, text/plain, */*',
            'Content-Type': 'application/json; charset=utf-8' },
         method: 'post',
         params:
          { agent: 'smartystreets (sdk:javascript@1.6.0)',
            'auth-id':  {correct auth id},
            'auth-token': {correct auth token} },
         baseURL: 'https://us-street.api.smartystreets.com/street-address',
         data:
          '[{"street":"330 N 100 W","street2":"closet under the stairs","secondary":"APT 2","city":"Provo","state":"Utah","zipcode":"84601","addressee":"John Doe","match":"invalid","candidates":3},{"street":"1600 Amphitheater Pkwy","lastline":"Mountainview, CA","candidates":5},{"street":"1600 Amphitheatre Parkway Mountain View, CA 94043","candidates":1}]',
         'axios-retry': { retryCount: 0, lastRequestTime: 1603858382613 },
         url: 'https://us-street.api.smartystreets.com/street-address' },
      request: XMLHttpRequest {} }

      at Axios.then.response (node_modules/smartystreets-javascript-sdk/src/HttpSender.js:49:14)

It has the correct auth-d and auth-token (I copied and pasted them into curl and postman requests from this log and those requests worked) but doesn't seem to authorize.  I even added the same agent param to postman and curl, and those requests work.

**Comment by enzoames** [comment]
Hey guys, I am having a very similar issue...

I'm using the javascript sdk to validate an address on the backend. By following the example (https://github.com/smartystreets/smartystreets-javascript-sdk/blob/master/examples/us_autocomplete_pro.js) I have

```js
import SmartyStreetsSDK from 'smartystreets-javascript-sdk';
const SmartyStreetsCore = SmartyStreetsSDK.core;
const Lookup = SmartyStreetsSDK.usAutocompletePro.Lookup;

const credentials = new SmartyStreetsCore.SharedCredentials(process.env.SS_WEB_KEY);
const client = SmartyStreetsCore.buildClient.usAutocompletePro(credentials);

export default async function handler(req, res) {
  const { address } = req.query;
  try {
    const lookup = new Lookup(address);
    const res = await client.send(lookup);
    console.log('res', res);
  } catch (err) {
    console.log('err::', err);
  }
 ...
}
```

and getting an authorization issue

```
err:: Response {
  statusCode: 401,
  payload: 'Unauthorized (1587658904)\n',
  error: BadCredentialsError: Unauthorized: The credentials were provided incorrectly or did not match any existing active credentials.
```

However, I'm doing a similar lookup on my front end code and works just fine (using the same key)

```js
...
const query = querystring.stringify({
  key: process.env.SS_WEB_KEY,
  license: 'us-autocomplete-pro-startup-cloud',
  search: inputValue,
  prefer_geolocation: 'CITY',
});

const res = await axios.get(`https://us-autocomplete-pro.api.smartystreets.com/lookup?${query}`);
...
```

Any idea why this could be happening?

**Comment by joliver** [comment]
The US Autocomplete Pro API only supports website key authentication:

https://smartystreets.com/docs/cloud/us-autocomplete-pro-api#pro-http-request-url
