### ISSUE TITLE
Configuring headers in auto complete pro while using sdk

### ISSUE THREAD

**Issue by rachanamamillapalli** [smartystreets/smartystreets-javascript-sdk#26]
In the auto-complete pro example, while building the client for lookup, is there any way we can configure the host/referer or request headers in general? The same goes for us-street validation as well.

```
const SmartyStreetsSDK = require("smartystreets-javascript-sdk");
const SmartyStreetsCore = SmartyStreetsSDK.core;
const Lookup = SmartyStreetsSDK.usAutocompletePro.Lookup;

let websiteKey = "put your website key here";
const credentials = new SmartyStreetsCore.SharedCredentials(websiteKey);

let client = SmartyStreetsCore.buildClient.usAutocompletePro(credentials);
```

The host is picked from the browser in most cases, but sometimes we see an empty host being passed due to which we get an "Unauthorised" error code.

**Comment by dave-smartystreets** [comment]
Can you provide some additional information about how to reproduce this problem?  Does it matter which browser you use?  When you say you sometimes see an empty host header, does that happen under certain reproducible conditions or when used with a certain browser?  Please let us know.  Thanks.

**Comment by rachanamamillapalli** [comment]
@dave-smartystreets Smarty streets returns Unauthorised error code sometimes when some customers of our app use this feature. It doesn't provide any details on why. However, in our logs we log the host/referrer from the browser which was empty when the validation API returned this Unauthorised code. So, I'm assuming the sdk also couldn't pick up the referrer due to which the error is thrown. 

I, while debugging, was not able to reproduce this error. The unauthorized code is also not seen very often but we do see them.

**Comment by dave-smartystreets** [comment]
@rachanamamillapalli, thanks for getting back.  

Does the problem happen consistently with the same customers?  It makes me wonder if certain customers might be using a browser extension that blocks the `referer` header like an ad blocker or other privacy oriented extension.  If it's happening to the same customers over and over again, they might have a firewall configuration that blocks or filters the `referer` header.  

The `referer` header cannot be manually set (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer), however you can try to govern how the browser sets it using the Referrer Policy (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy).  On the link about the Referrer Policy, it talks about using the `<meta name="referrer" content="origin">` in your html.  It may be worthwhile setting it to something more strict.

Google Chrome recently changed their Referrer Policy to be more strict (see https://developers.google.com/web/updates/2020/07/referrer-policy-new-chrome-default).  This article is also useful for understanding the security and privacy implications of the `referer` header.

Please let me know if this helps.
