### ISSUE TITLE
'length' of undefined on buildUsAutocompleteProClient

### ISSUE THREAD

**Issue by ronssij** [smartystreets/smartystreets-javascript-sdk#27]
![image](https://user-images.githubusercontent.com/24932380/104324883-f570ee00-5522-11eb-9c7b-022e12a262ea.png)

![image](https://user-images.githubusercontent.com/24932380/104325344-7fb95200-5523-11eb-9941-715f67706afd.png)

but when I use the `buildUsAutocompleteClient()` seems to be working on my end.

and I am blocked by this issue on Pro.

**Comment by ronssij** [comment]
Closing the issue

I used the `new SmartyStreetsSDK.usAutocomplete.Lookup(lookup);` instead of `new SmartyStreetsSDK.usAutocompletePro.Lookup(lookup);`

**Comment by martinmckenna** [comment]
This needs to be re-opened. not sure why a lot of these class props are seemingly required because the code assumes they will always be defined, when they don't need to be

**Comment by camiblanch** [comment]
@martinmckenna Can you reference which class and class props you are referring to?

**Comment by martinmckenna** [comment]
actually false alarm this was user error
