### ISSUE TITLE
US Streets Client throws response.payload.map is not a function error

### ISSUE THREAD

**Issue by jackjwilliams** [smartystreets/smartystreets-javascript-sdk#3]
When I send a US Street lookup, I get the following error:

```
TypeError: response.payload.map is not a function
    at assignResultsToLookups (sendBatch.js:31)
    at sender.send.then.response (sendBatch.js:19)
    at tryCallOne (core.js:37)
    at core.js:123
    at MutationObserver.flush (browser-raw.js:52)
```

Query String params:

street: 2330 Whitney Dr
city: Monroe
state: LA
match: invalid

When debugging, I see that in assignResultsToLookups, the "response" param is structured as:

```
{  
   "statusCode":200,
   "payload":{  
      "suggestions":null
   }
}
```

Should it not be calling response.payload.suggestions.map with a null check on suggestions?

**Comment by jackjwilliams** [comment]
Possibly related to https://github.com/smartystreets/smartystreets-javascript-sdk/issues/1 (or similar to it)

**Comment by jackjwilliams** [comment]
This may be a non-issue. Turns out, I was trying to re-use the shared credentials from autocomplete with streets API, and it was calling a different address, which was returning strange results.

**Comment by cbuchert** [comment]
Glad you got it sorted out. I'd be interested in seeing your wire up just in case. Feel free to send it my way.
