### ISSUE TITLE
Non-postal address support

### ISSUE THREAD

**Issue by scottbullard** [smartystreets/smartystreets-javascript-sdk#36]
The current version seems to lack support for the [Non-postal address](https://github.com/smartystreets/changelog/blob/master/cloud/us-autocomplete-pro-api.md#161---2021-08-03).

**Comment by camiblanch** [comment]
@scottbullard This SDK has support for non-postal addresses. To use it you must have an active US Core license or a US Rooftop Geocoding license, [set the license on the client builder](https://github.com/smartystreets/smartystreets-javascript-sdk/blob/master/examples/us_street.js#L17), and set `lookup.match` to `enhanced` before making a request.

**Comment by camiblanch** [comment]
The response is set on `candidate.analysis.enhancedMatch` as seen here https://github.com/smartystreets/smartystreets-javascript-sdk/blob/master/src/us_street/Candidate.js#L83

**Comment by scottbullard** [comment]
@camiblanch - sorry for not being more specific. Does this apply for the `usAutocompletePro` client? I do not see this as an [available parameter](https://github.com/smartystreets/smartystreets-javascript-sdk/blob/master/src/us_autocomplete_pro/Client.js#L32).

**Comment by camiblanch** [comment]
@scottbullard The SDK does not have support for using non-postal addresses yet, but we are currently working on implementing that. It is available in the [US Autocomplete Pro API](https://www.smartystreets.com/docs/cloud/us-autocomplete-pro-api#input-source) directly. I will keep this issue open until the support is added

**Comment by swiatekr** [comment]
@camiblanch @DuncanBeutler When are you planning to roll out this update?

**Comment by camiblanch** [comment]
@swiatekr Yes sorry we meant to update this issue once we published the changes. This was fixed in pull request #37 and published in version 1.11.0
