### ISSUE TITLE
Recent version of axios-retry dependency breaks due to missing peerDep

### ISSUE THREAD

**Issue by tombakerjr** [smartystreets/smartystreets-javascript-sdk#38]
Version 3.2.1 of `axios-retry` made a breaking change that requires `axios` as a `peerDependency`. This causes the `HttpSender` to throw an exception when it's called e.g. in `buildUsAutocompleteProClient()`.

https://github.com/softonic/axios-retry/blob/master/CHANGELOG.md#321---2021-10-14

**Comment by qiquanlu** [comment]
@camiblanch,  I added "axios-retry": "3.2.0" yesterday and it worked with 1.11.0, but it's no longer working after your 1.11.2 release. Could you check this again? It seems axios-retry 3.2.3 still has some conflict, 3.2.0 works perfectly fine. Thanks

**Comment by qiquanlu** [comment]
> Just published live to 1.11.3, let me know if you are still experiencing issues after moving to that version

I can confirm  1.11.3 works fine, thank you!
