### ISSUE TITLE
"Syntax Error"  when using ES6 npm library in angular 7 app

### ISSUE THREAD

**Issue by sir-captainmorgan21** [smartystreets/smartystreets-javascript-sdk#4]
![image](https://user-images.githubusercontent.com/7041924/51362740-d447a500-1aa2-11e9-8ba3-df522564e89f.png)

![image](https://user-images.githubusercontent.com/7041924/51362778-f0e3dd00-1aa2-11e9-9b6f-36533613079f.png)

I get the above console error when using the library from your npm package. I only get this error in IE11

**Comment by cbuchert** [comment]
@sir-captainmorgan21 The SDK is written in ES6, which IE11 will not interpret. You'll need to Babelify your JS in order to get it running on IE11 and other older browser versions that don't support IE11.

https://babeljs.io/
https://babeljs.io/docs/en/babel-preset-env

**Comment by sir-captainmorgan21** [comment]
@cbuchert can you not provide support for IE11 in your library?

**Comment by mdwhatcott** [comment]
@sir-captainmorgan21 - Well, we certainly could, but [we've chosen not to](https://smartystreets.com/docs/sdk/javascript#requirements). As @cbuchert mentioned above, using babel is the recommended workaround.
