### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by mnalsup** [smartystreets/smartystreets-javascript-sdk#7]
I use typescript when possible and I have written some basic definitions for this SDK. I would like to contribute them to this repository if possible. Feedback on the idea and then the definitions themselves would be awesome!

**Comment by cbuchert** [comment]
That sounds fantastic, @mnalsup! Will you put together a pull request? We'll work with you to get it into the SDK.

**Comment by cbuchert** [comment]
This functionality will be revisited should the SDK be moved over to TypeScript.

**Comment by kkikta-bcg** [comment]
https://www.npmjs.com/package/@types/smartystreets-javascript-sdk

**Comment by newbish** [comment]
https://www.npmjs.com/package/@types/smartystreets-javascript-sdk
