### ISSUE TITLE
Export usStreets Candidate constructor

### ISSUE THREAD

**Issue by mnalsup** [smartystreets/smartystreets-javascript-sdk#8]
I am writing some tests validating the correct handling of the usStreets Candidate class. It would be really helpful to have a handle on the constructor for this class for building cases. Would this be possible/appropriate?

**Comment by cbuchert** [comment]
@mnalsup we're always up for community contribution. I'm unfamiliar with handles on a class constructor. Will you go into more detail and include examples to help us better understand your objectives and challenges?

**Comment by mnalsup** [comment]
Sorry, that was probably poor phrasing on my part. It would be helpful to have the US_Street Candidate class exported so I can create instances of it for testing purposes. Currently, only the Lookup class is exported.

**Comment by cbuchert** [comment]
Got it. I can bump that out for you quick or you can make a pull request quick and I'll review it if you want the credit.
